// AstrCode - Agent orchestration engine for AstrBot
// Copyright (C) 2026 EterUltimate
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package codegen

import (
	"context"
	"fmt"

	"github.com/EterUltimate/astrcode/internal/llm"
	"github.com/EterUltimate/astrcode/internal/model"
)

// Generator 代码生成引擎
// 基于 LLM 和 AstrBot SDK 模板生成插件代码
type Generator struct {
	llmClient *llm.Client
}

// NewGenerator 创建代码生成器
func NewGenerator(llmClient *llm.Client) *Generator {
	return &Generator{
		llmClient: llmClient,
	}
}

// PluginSpec 插件规格定义
type PluginSpec struct {
	Name         string            // 插件名称
	Description  string            // 功能描述
	Handlers     []HandlerSpec     // 处理器列表
	Config       map[string]string // 配置项
	Dependencies []string          // 依赖库
}

// HandlerSpec 处理器规格
type HandlerSpec struct {
	Name        string
	EventType   string // message/command/etc
	Description string
	Parameters  []string
}

// GeneratedPlugin 生成的插件
type GeneratedPlugin struct {
	Files      map[string]string // 文件名 -> 内容
	PluginYaml string
	MainPy     string
	Tests      map[string]string
	Spec       *PluginSpec
}

// GeneratePlugin 根据自然语言需求生成完整插件
func (g *Generator) GeneratePlugin(ctx context.Context, requirement string, skills []model.Skill) (*GeneratedPlugin, error) {
	// 1. 分析需求，提取插件规格
	spec, err := g.analyzeRequirement(ctx, requirement, skills)
	if err != nil {
		return nil, fmt.Errorf("analyze requirement failed: %w", err)
	}

	// 2. 生成 plugin.yaml
	pluginYaml, err := g.generatePluginYaml(spec)
	if err != nil {
		return nil, fmt.Errorf("generate plugin.yaml failed: %w", err)
	}

	// 3. 生成 main.py
	mainPy, err := g.generateMainPy(spec)
	if err != nil {
		return nil, fmt.Errorf("generate main.py failed: %w", err)
	}

	// 4. 生成测试文件
	tests, err := g.generateTests(spec)
	if err != nil {
		return nil, fmt.Errorf("generate tests failed: %w", err)
	}

	return &GeneratedPlugin{
		Files: map[string]string{
			"plugin.yaml": pluginYaml,
			"main.py":     mainPy,
		},
		PluginYaml: pluginYaml,
		MainPy:     mainPy,
		Tests:      tests,
		Spec:       spec,
	}, nil
}

// analyzeRequirement 分析自然语言需求，提取插件规格
func (g *Generator) analyzeRequirement(ctx context.Context, requirement string, skills []model.Skill) (*PluginSpec, error) {
	prompt := fmt.Sprintf(`你是一个 AstrBot 插件架构师。根据以下需求，设计插件结构。

需求：%s

可用 Skills：%v

请输出 JSON 格式的插件规格，包含：
- name: 插件名称（英文，小写+下划线）
- description: 简短描述
- handlers: 处理器列表 [{name, event_type, description, parameters}]
- config: 配置项 {key: description}
- dependencies: 依赖库列表

只输出 JSON，不要其他内容。`, requirement, skills)

	resp, err := g.llmClient.Complete(ctx, prompt)
	if err != nil {
		return nil, err
	}
	_ = resp // TODO: 解析 JSON 响应

	// TODO: 解析 JSON 响应为 PluginSpec
	// 这里简化处理，实际需要使用 json.Unmarshal
	spec := &PluginSpec{
		Name:        "generated_plugin",
		Description: requirement,
		Handlers: []HandlerSpec{
			{
				Name:        "handle_message",
				EventType:   "message",
				Description: "处理用户消息",
			},
		},
		Config:       make(map[string]string),
		Dependencies: []string{},
	}

	return spec, nil
}

// generatePluginYaml 生成 plugin.yaml 配置文件
func (g *Generator) generatePluginYaml(spec *PluginSpec) (string, error) {
	yaml := fmt.Sprintf(`name: %s
version: 0.1.0
description: %s
author: AstrCode Generated
handlers:
`, spec.Name, spec.Description)

	for _, h := range spec.Handlers {
		yaml += fmt.Sprintf("  - type: %s\n    name: %s\n", h.EventType, h.Name)
	}

	if len(spec.Dependencies) > 0 {
		yaml += "dependencies:\n"
		for _, dep := range spec.Dependencies {
			yaml += fmt.Sprintf("  - %s\n", dep)
		}
	}

	return yaml, nil
}

// generateMainPy 生成主逻辑文件
func (g *Generator) generateMainPy(spec *PluginSpec) (string, error) {
	code := fmt.Sprintf(`"""
%s
Generated by AstrCode
"""

from astrbot.api import *
from astrbot.api.event import filter
import logging

logger = logging.getLogger(__name__)


@register(name="%s", description="%s", version="0.1.0", author="AstrCode")
class %sPlugin(Star):
    def __init__(self, context: Context, config: AstrBotConfig):
        super().__init__(context)
        self.config = config
        logger.info("%s plugin initialized")

`, spec.Description, spec.Name, spec.Description,
		capitalize(spec.Name), spec.Name)

	// 生成处理器
	for _, h := range spec.Handlers {
		code += fmt.Sprintf(`    @%s
    async def %s(self, event: AstrMessageEvent):
        """%s"""
        try:
            # TODO: 实现业务逻辑
            message = event.message_str
            await event.send(f"收到消息: {message}")
        except Exception as e:
            logger.error(f"Error in %s: {e}")
            await event.send(f"发生错误: {str(e)}")

`, h.EventType, h.Name, h.Description, h.Name)
	}

	return code, nil
}

// generateTests 生成测试文件
func (g *Generator) generateTests(spec *PluginSpec) (map[string]string, error) {
	testCode := fmt.Sprintf(`"""Tests for %s plugin"""
import pytest
from unittest.mock import Mock, AsyncMock


@pytest.mark.asyncio
async def test_%s():
    """测试基本功能"""
    # TODO: 编写测试用例
    assert True
`, spec.Name, spec.Handlers[0].Name)

	return map[string]string{
		"test_main.py": testCode,
	}, nil
}

// capitalize 首字母大写
func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}
	return string(s[0]-32) + s[1:]
}
