// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeployPlugin(arg1:string,arg2:string):Promise<string>;

export function GenerateCode(arg1:string):Promise<string>;

export function GetHealth():Promise<string>;

export function GetSkills():Promise<string>;

export function GetVersion():Promise<string>;

export function MCPGetDoc(arg1:string,arg2:string):Promise<string>;

export function MCPGetHookInventory():Promise<string>;

export function MCPListDocs(arg1:string):Promise<string>;

export function MCPSearchDocs(arg1:string):Promise<string>;

export function ReviewCode(arg1:string):Promise<string>;

export function RuntimeGetOutput():Promise<string>;

export function RuntimeGetStatus():Promise<string>;

export function RuntimeStart(arg1:string):Promise<string>;

export function RuntimeStop():Promise<string>;
