// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeployPlugin(arg1, arg2) {
  return window['go']['main']['App']['DeployPlugin'](arg1, arg2);
}

export function GenerateCode(arg1) {
  return window['go']['main']['App']['GenerateCode'](arg1);
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function MCPGetDoc(arg1, arg2) {
  return window['go']['main']['App']['MCPGetDoc'](arg1, arg2);
}

export function MCPGetHookInventory() {
  return window['go']['main']['App']['MCPGetHookInventory']();
}

export function MCPListDocs(arg1) {
  return window['go']['main']['App']['MCPListDocs'](arg1);
}

export function MCPSearchDocs(arg1) {
  return window['go']['main']['App']['MCPSearchDocs'](arg1);
}

export function ReviewCode(arg1) {
  return window['go']['main']['App']['ReviewCode'](arg1);
}

export function RuntimeGetOutput() {
  return window['go']['main']['App']['RuntimeGetOutput']();
}

export function RuntimeGetStatus() {
  return window['go']['main']['App']['RuntimeGetStatus']();
}

export function RuntimeStart(arg1) {
  return window['go']['main']['App']['RuntimeStart'](arg1);
}

export function RuntimeStop() {
  return window['go']['main']['App']['RuntimeStop']();
}
